server:
  port: 8085
  servlet:
    context-path: /api/v1/fuel-detail

spring:
  active-mq:
    user: admin
    password: admin
    broker-url: tcp://localhost:61617

fuel:
  service:
    queue: FUEL.DETAIL.QUEUE